### ISSUE TITLE
If you read the data multiple times, you won't be able to read the data

### ISSUE THREAD

**Issue by childeyouyu** [pyhys/minimalmodbus#127]
```
    while True:
        read_data = inst.read_float(registeraddress=1, number_of_registers=2, functioncode=3)
        print(read_data)
        time.sleep(1)
```
I need to consistently read the data in the device, but frequently, it will not read the data.
Like this:
minimalmodbus.NoResponseError: No communication with the instrument (no answer)

**Comment by arthurtaras** [comment]
Increase the sleep time to 50 and see if errors still appear. If not decrease to 25, 10, 5 and so on. Chances are you are overdriving it too fast either on the processor or microcontroller side

**Comment by childeyouyu** [comment]
@arthurtaras Do you mean 50s? This is too long a wait time for me, and I need to record a lot of data on demand.

**Comment by j123b567** [comment]
Did you follow all instructions in [Serial communication][1] and [Troubleshooting][2]?

[1]: https://minimalmodbus.readthedocs.io/en/stable/serialcommunication.html
[2]: https://minimalmodbus.readthedocs.io/en/stable/troubleshooting.html

**Comment by arthurtaras** [comment]
@childeyouyu just test it with 10, 5, 2 and see if the frequency of errors goes up or down. Do you have access to the code on the microcontroller? To read more data more frequently you would need to optimize the other side

**Comment by childeyouyu** [comment]
> @childeyouyu just test it with 10, 5, 2 and see if the frequency of errors goes up or down. Do you have access to the code on the microcontroller? To read more data more frequently you would need to optimize the other side

I  will try it tomorrow.

**Comment by j123b567** [comment]
IMHO longer `time.sleep` will not help here.
 - if your device is slow, you can try to play with `inst.serial.timeout` instead
 - if your device does not respect frame gap or has other bugos behavior then you should repeat the request immediately without waiting. The device missed the request already so waiting for the response longer make no sense here.
 - if you have wrong communication setup e.g. unsupported RS-485 transiever, wrong cabeling, ... then just replace the wrong hardware. There is no other help here. See troubleshooting mentoned earlier.

**Comment by childeyouyu** [comment]
@j123b567 
It works, I set `inst.serial.timeout` to 1, the program reads a thousand lines in a row without the previous error, I will test the program all the way to the official program code, and if available, I will close this issue.
So is this due to a problem with my device's performance?

**Comment by j123b567** [comment]
@childeyouyu There is nothing particularly wrong with that. Some devices even add a programmable delay before responding. You can try a much smaller number than 1 second, e.g. `0.03` or even `0.01` might do. Setting this to 1 can make the whole communication unnecessarily slow.
