### ISSUE TITLE
Parity configuration in documentation is wrong

### ISSUE THREAD

**Issue by HWHardsoft** [pyhys/minimalmodbus#128]
Hi,

in the documentation parity configuration is decribed so:

instrument.serial.parity   = serial.PARITY_NONE

This is not working! The right way:

instrument.serial.parity   = 'N'

Please change the documentation.

Thx

**Comment by j123b567** [comment]
Did you forget to `import serial`?

`serial.PARITY_NONE` is `'N'`, see https://github.com/pyserial/pyserial/blob/master/serial/serialutil.py#L79
