### ISSUE TITLE
Slave errors should be a distinct exception

### ISSUE THREAD

**Issue by austinbes** [pyhys/minimalmodbus#21]
Having errors from the slave be `ValueError` exceptions makes it hard to discriminate between protocol problems (slave errors and the like) and internal errors (coding mistakes, etc).

It might be nice if there were a separate class of exceptions (like `ModbusError`) which were thrown when slave errors occur, so one could do something like

```python
try:
    instrument.write_register(whatever, a_value)
except minimalmodbus.ModbusError:
    # Handle the error somehow
```

**Comment by pyhys** [comment]
Duplicate of pull request #8
