### ISSUE TITLE
I want to know how much delay can be achieved in continuous reading and writing.

### ISSUE THREAD

**Issue by leytonxu** [pyhys/minimalmodbus#34]
When I tried to read and write registers, I found that it would report errors when "time.sleep()" is too short.

**Comment by ssshah86** [comment]
It is dependent on your `baud_rate`. There must be 3.5 character silent period, see [here](https://github.com/pyhys/minimalmodbus/blob/master/minimalmodbus.py#L865). 

The clocks on your slave and master may not be synchronized so this is a minimum. You can also try running and testing lower sleep times until you achieve the performance desired. Good luck.

**Comment by pyhys** [comment]
In next release the sleep time will be increased for some of the higher baud rates. See #25.
