### ISSUE TITLE
Read Multiple coils?

### ISSUE THREAD

**Issue by Devangsavla** [pyhys/minimalmodbus#35]
I may be missing out on something basic but for some reason, I can't find a direct way to read multiple coils using minimalmodbus. I read the documentation, StackExchange pages, and even this Github project.
Like to read multiple registers you use read_registers() instead of read_register. Why isn't there a read_coils() function along with read_coil().
As a way around this, I have to manually write the whole packet over serial and read its reply back. This even though is functional, is too tedious to maintain.
Please help me understand if I am missing something silly.

Thank you.

**Comment by ssshah86** [comment]
Can you close this and keep all the comments in https://github.com/pyhys/minimalmodbus/issues/27? It will help keep the discussion focused.

Other people are also having the issue, hopefully we can solve it together soon.
