### ISSUE TITLE
write_register pauses indefinitely when no slave is connected

### ISSUE THREAD

**Issue by austinstover** [pyhys/minimalmodbus#36]
### System information
- **OS Platform**: Windows 10
- **python version**: 3.6.5
- **minimalmodbus version**: 0.7.0
- **Directions to reproduce**: Use [com0com](http://com0com.sourceforge.net/) to create a virtual serial port (for testing purposes). Then run this code: 
```python
import minimalmodbus as mb

def main():
    mb.BAUDRATE = 9600
    mb.TIMEOUT = 0.1
    slave = mb.Instrument('COM8', 0)
    print("Start Write")
    slave.write_register(1, 0b100, functioncode=6) #Program hangs here
    print("Done")

if __name__ == '__main__':
    main()
```

### Problem
Minimalmodbus pauses indefinitely when `write_register` is called without a slave connected. I tested this with a virtual serial port, but I'm pretty sure it also happened once when I was using an actual serial port and the Arduino microcontroller I was talking to was off. I did a bit of print-statement testing and it looks like the problem occurs within `_genericCommand`.

**Comment by pyhys** [comment]
The write() in pyserial is blocking by default. It is possible to define a write timeout, after which an exception is raised.

`instrument.serial.write_timeout=2.0`

See https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.write

**Comment by pyhys** [comment]
There will be an write timeout in next release.
