### ISSUE TITLE
Read and write flag registers

### ISSUE THREAD

**Issue by cristianlivella** [pyhys/minimalmodbus#40]
Hi. I want to use MinimalModbus to control some fan coil unit. According to the manufacturer manual, there are integer registers, decimal registers and also flags register, composed by more boolean value. How can I read and write that registers? I have to read the registers as simple integer, and then parse to binary to get the flags, and vice versa to write? Thanks

**Comment by pyhys** [comment]
Hi, yes you are right. I will update the documentation in next release:

Some manufacturers use 16-bit registers to store individual boolean values (bits), so with 
a single read from a single address, 16 booleans could be retrieved.
This is sometimes called a flag register.

You need to read the register as an integer, and then 
extract the bit you are interested in. For example to extract the 
third bit from right::

    registervalue = instrument.read_register(4143)
    is_my_bit_set = (registervalue & 0b0000000000000100) > 0

or if using hexadecimal numbers in your code instead::

    is_my_bit_set = (registervalue & 0x0004) > 0

More information on bit manipulation in Python, see the "Single bits" section 
of https://wiki.python.org/moin/BitManipulation
