### ISSUE TITLE
Package dummy_serial.py again

### ISSUE THREAD

**Issue by geowiwi** [pyhys/minimalmodbus#44]
Hi,

For running tests/, it would be useful to repackage dummy_serial.py again in the .tar.gz file for pypi, as was done back in 0.7. This would make it easier to run tests from the OpenBSD ports frameworks (using it there with an SDM630 and an Eurotherm TE200A).

Thanks!
-m

**Comment by pyhys** [comment]
Great idea.
It will be included in next release.
