### ISSUE TITLE
read_bit does interprets wrong response part

### ISSUE THREAD

**Issue by marvinosswald** [pyhys/minimalmodbus#5]
Is it a bug, or am i doing something wrong ?

My code:
```
i = DeltaDVP.DeltaDVP('/dev/tty.usbserial-AI02L43I', 1)
i.read_bit(0x502,functioncode=1)
```

Debug Output:
```
MinimalModbus debug mode. Writing to instrument (expecting 13 bytes back): ':010105020001F6\r\n' (3A 30 31 30 31 30 35 30 32 30 30 30 31 46 36 0D 0A)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 204687.4 ms, minimum silent period: 4.01 ms.
MinimalModbus debug mode. Response from instrument: ':01010103FA\r\n' (3A 30 31 30 31 30 31 30 33 46 41 0D 0A) (13 bytes), roundtrip time: 40.3 ms. Timeout setting: 50.0 ms.
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/minimalmodbus.py", line 193, in read_bit
    return self._genericCommand(functioncode, registeraddress)
  File "/usr/local/lib/python2.7/site-packages/minimalmodbus.py", line 726, in _genericCommand
    return _bitResponseToValue(registerdata)
  File "/usr/local/lib/python2.7/site-packages/minimalmodbus.py", line 1770, in _bitResponseToValue
    raise ValueError('Could not convert bit response to a value. Input: {0!r}'.format(bytestring))
ValueError: Could not convert bit response to a value. Input: '\x03'
>>> 
```

**Comment by pyhys** [comment]
Hej Marvin,
yes this seems to be a bug in your instrument.

This is sent: 

MinimalModbus debug mode. Writing to instrument (expecting 13 bytes
back): ':010105020001F6\r\n'
The payload is 05020001, where:
0502 Start address
0001 Number of bits


The response is:

MinimalModbus debug mode. Response from instrument: ':01010103FA\r\n'
(3A 30 31 30 31 30 31 30 33 46 41 0D 0A) (13 bytes


It has the payload 0103, where:
01 Byte count
03 Value  (binary 0000 0011)

We ask for a single bit, but the response has more than one bit set.
That is out of specification.

As a workaround, you can parse the response yourself instead. See:
https://minimalmodbus.readthedocs.org/en/master/develop.html#extending-m
inimalmodbus
<http://https://minimalmodbus.readthedocs.org/en/master/develop.html#ext
ending-minimalmodbus> 

You then need to catch up on the Modbus details:
https://minimalmodbus.readthedocs.org/en/master/modbusdetails.html
<http://https://minimalmodbus.readthedocs.org/en/master/modbusdetails.ht
ml> 

Best regards
Jonas








<-----Ursprungligt Meddelande----->
