### ISSUE TITLE
Cannot change baud rate when extending

### ISSUE THREAD

**Issue by Boo1098** [pyhys/minimalmodbus#53]
Currently the only way to change the baud rate when extending minimalmodbus.Instrument is by doing something like this:

```python3
import minimalmodbus
 
class myInstrument(minimalmodbus.Instrument):
    def __init__(self, port, slaveaddress, baudrate):
        minimalmodbus.Instrument.__init__(self, port, slaveaddress)
        self.serial._baudrate=9600
```

This is not ideal since _baudrate should be protected. Is there a reason baud rate is not a parameter in the constructor?

**Comment by j123b567** [comment]
Why are you using protected member? Just simply set baudrate by `self.serial.baudrate=9600`.

Serial port is shared between `Instrument` instances so if it will be in the constructor, it can evoke false impression, that you can configure different communication parameters for every instrument on the same bus, which is not true.
