### ISSUE TITLE
How to measure round trip time

### ISSUE THREAD

**Issue by tr-gis** [pyhys/minimalmodbus#63]
Is there a function among the APIs that will return round trip time for a function call?.

**Comment by ccall48** [comment]
https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.debug

From memory this gives transaction time.

**Comment by tr-gis** [comment]
Hi @ccall48 . I have seen roundtrip times displayed as part of debug output. I am looking for function calls that will return round trip time, with debug option set to True, it only prints the time.

**Comment by pyhys** [comment]
@tr-gis There is unfortunately no plans to adjust the official API with this functionality, but you can yourself write to some new attribute of the `Instrument` each time you get a response.

**Comment by pyhys** [comment]
I did actually include this in the latest release:
https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.roundtrip_time
