### ISSUE TITLE
Too short start of frame

### ISSUE THREAD

**Issue by DaveCalaway** [pyhys/minimalmodbus#64]
I wrote a simple program to read a slave device. There are other master on the sys.
When i try to read a register with a command:
`temperature = instrument.read_register(2000) `
i receive this message:
```
MinimalModbus debug mode. Will write to instrument (expecting 7 bytes back): '*\x03\x07Ð\x00\x01\x82\x9c' (2A 03 07 D0 00 01 82 9C)
MinimalModbus debug mode. Clearing serial buffers for port COM30
MinimalModbus debug mode. No sleep required before write. Time since previous read: 3000.00 ms, minimum silent period: 4.01 ms.
MinimalModbus debug mode. Response from instrument: '*\x06\x084\x00\x00Ì' (2A 06 08 34 00 00 CC) (7 bytes), roundtrip time: 0.0 ms. Timeout for reading: 50.0 ms.
```
The read goes well only in 1/20 cases.

If i take a look at the capture i have this result:
![Cattura](https://user-images.githubusercontent.com/10884164/111457425-76618700-8718-11eb-8724-f4c48e24c0af.JPG)

The software does't takes care about the other frames. 
In this capture the program starts to write during a request addr 0x35.
It's looks like that it starts to request without wait the stop frames from the other messages.

I'm using an RS485 to serial with a terminal resistor, plus those parameters:
```
        instrument.serial.baudrate = 9600         # Baud
        instrument.serial.bytesize = 8
        instrument.serial.parity = minimalmodbus.serial.PARITY_NONE
        instrument.serial.stopbits = 2
        instrument.serial.timeout  = 0.05          # seconds
        instrument.mode = minimalmodbus.MODE_RTU   # rtu or ascii mode
        instrument.clear_buffers_before_each_transaction = True
```

**Comment by j123b567** [comment]
Modbus RTU does not support multimaster setup. So try it with just one master in the system.
