### ISSUE TITLE
Are the BYTEORDER_*_SWAP constants the wrong way round?

### ISSUE THREAD

**Issue by acetylen** [pyhys/minimalmodbus#73]
I'm communicating with a rebranded Carlo Gavazzi EM340DINAV23XS1PFA power meter, which is a bit quirky, so this may be a flub on their part. [Here's the programmer manual I'm using](http://www.garo.se/storage/ma/e6fe0c38363f490c9ab35eb996b4ee07/f88b91a174ac49f7807e0291b29a53a1/pdf/5/108047_5_Protocol%20GNM3D,-T%20Modbus.pdf).

Reading out raw data for the system line voltage (which is an INT32 with a scaling factor of 10) by using `read_registers(0x24, 2)` I get `091e 0000`, which to me reads like 2334 in big endian with the words swapped. Since this is a 220-240V system, that seems like a reasonable value.

However, doing `read_long(addr, signed=True, byteorder=BYTEORDER_BIG_SWAP)` results in 0x1e090000, which is little endian. Switching to BYTEORDER_LITTLE_SWAP gives back 0x0000091e.

I'm using minimalmodbus 2.0.1 off of pypi with python 3.7.3 on debian 10.10. The `Instrument` has no special constructor arguments, just device file and baudrate.

**Comment by acetylen** [comment]
If that's how it's supposed to be read, then yes. My reading of the constant name BYTEORDER_LITTLE_SWAP was "interpret bytes as little endian, and swap word order". Since the inner byte order is big endian, I assumed that BYTEORDER_BIG_SWAP was the correct one. This could probably be mitigated by just documenting the exact effect of the values then.

I would probably have designed it to explicitly use one bit for byte order and one for word order, so that you could do `BYTEORDER_BIG | WORDORDER_LITTLE`. It looks like the values can already be used like that since both LITTLE values have bit 1 set.

**Comment by j123b567** [comment]
You mean documentation like this? https://minimalmodbus.readthedocs.io/en/stable/modbusdetails.html#byte-order-for-data-stored-in-serveral-registers
It is already there

**Comment by acetylen** [comment]
Hah, exactly! Serves me right for jumping directly to the API docs and source code when I encountered a problem.
