### ISSUE TITLE
How to add caracter NULL in minimalmodbus.write_string() ?

### ISSUE THREAD

**Issue by patfrench** [pyhys/minimalmodbus#76]
Hi,

I try to place a null caracter terminator in

write_string(0x1402,"SIMTRO698\0",6)

is it possible ?

Thank you

**Comment by j123b567** [comment]
Did you try it already? Do you have any issues?

You are writing 6 registers but your string is 5 registers log, so it will be padded by spaces as stated in documentation. If you need it to be padded by zeros, you should use "SIMTRO698\0\0\0"
