### ISSUE TITLE
For custom function codes via the `_perform_command()` function, is there a way to force how many payload bytes are returned?

### ISSUE THREAD

**Issue by emptor8** [pyhys/minimalmodbus#77]
If I use a custom function code, `_perform_command()` doesn't return the correct payload data (debug mode shows the correct data, however). Is there a way to force the number of payload bytes returned, or to just get the raw data returned and let me parse stuff myself? :)

For example, in the call below, I'm expecting a payload return of 0x33, 0x44 but the return value is 0x3D for some reason instead:

>MinimalModbus debug mode. Create serial port COM7
MinimalModbus debug mode. Will write to instrument (expecting 1000 bytes back): 01 20 11 F9 CC (5 bytes)
MinimalModbus debug mode. Clearing serial buffers for port COM7
MinimalModbus debug mode. No sleep required before write. Time since previous read: 93392343.00 ms, minimum silent period: 1.75 ms.
MinimalModbus debug mode. Response from instrument: 01 20 33 44 14 D1 (6 bytes), roundtrip time: 0.0 ms. Timeout for reading: 50.0 ms.
result:3D

**Comment by j123b567** [comment]
The response is right!
ASCII 3 is 0x33
ASCII D is 0x44

It is limitation caused by historical decision of using `str` and not `bytes` for representing bytes (#74)

Just convert response to bytes by `.encode("latin1")`

```python
response = instr._perform_command(....).encode("latin1")

# print hex codes of response
from binascii import hexlify
print(hexlify(response))
```

**Comment by emptor8** [comment]
Ah excellent, thanks.
