### ISSUE TITLE
Function code 16 not accepting integers for `Float` payload anymore

### ISSUE THREAD

**Issue by alihamdan** [pyhys/minimalmodbus#78]
The commit [type checking with mypy](https://github.com/pyhys/minimalmodbus/commit/a3a223c82004b592163d2f1e40554fe01a105540) introduced a regression where Float payloads with function code 16 no longer accept integer values.
This behavior is caused by this assert statement https://github.com/pyhys/minimalmodbus/blob/185afffd2d65b585f69bc5e3f640270d2bd27444/minimalmodbus.py#L1619-L1621

I believe this should allow int values as the underlying `struct.pack` handles the conversion.

**Comment by pyhys** [comment]
Fixed in the latest release. 
Thanks for the report!
