### ISSUE TITLE
Sniff on SCADA systems...

### ISSUE THREAD

**Issue by Carmzy** [pyhys/minimalmodbus#89]
Is it possible to sniff on ICS using my bear laptop and wifi extender? Is is possible to sniff on modbus remotely such as the nearest electrical power plant near me? thanks

**Comment by j123b567** [comment]
It depends. But it is deffinitely out of the scope of this issue tracker.

**Comment by arthurtarasov** [comment]
@Carmzy No, you cannot sniff it for the same reason you cannot sniff TCP IP over ethernet. It has little to do with Modbus or TCP applications. The link layer, the transceivers, are differential and the physical layer, wires, are twisted. So you have two twisted wires and any signal pulls one wire to positive voltage and the other to negative. The outside electromagnetic field doesn't change whether one or zero bit is transmitted. You could "sniff" it if you touch the wires with a probe, but if you have physical access to the system then the topic of sniffing is moot

**Comment by j123b567** [comment]
> > It depends. But it is deffinitely out of the scope of this issue tracker.
> 
> Can you explain more elaborately?

No. Please ask on hacker forums and not there. It is completely offtopic and potentialy illegal.
